version: '3.8'

networks:
  client:
    name: client
    driver: overlay

  gateway:
    name: gateway
    external: true

services:
  app:
    build:
      context: ./
      dockerfile: ./.docker/prod/app/Dockerfile
    image: ${IMAGE_REGISTRY:-local}/client-app:${IMAGE_TAG:-latest}
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      VIRTUAL_PORT: 3000
      VIRTUAL_PROTO: https
    hostname: client
    expose:
      - 3000
    ports:
      - "3000:3000"
    networks:
      - client
      - gateway
    restart: unless-stopped
