version: '3.8'

# List of used networks
networks:
  # The client network
  client:
    name: client
    driver: overlay

#  # The API network
#  api:
#    name: api
#    external: true

# List of used services
services:
  # The client application container
  app:
    build:
      context: ./
      dockerfile: ./.docker/prod/app/Dockerfile
    image: ${IMAGE_REGISTRY:-local}/client-app:${IMAGE_TAG:-latest}
#    environment:
#      VIRTUAL_HOST: ${VIRTUAL_HOST}
#      VIRTUAL_PORT: 3000
    hostname: client
    expose:
      - 3000
    ports:
      - "3000:3000"
    networks:
      - client
#      - api
    restart: unless-stopped
