version: '3.8'

networks:
  gateway:
    name: gateway
    external: true

  client:
    name: client
    driver: overlay

services:
  app:
    image: ${IMAGE_REGISTRY:-local}/client-app:${IMAGE_TAG:-latest}
    build:
      context: ./
      dockerfile: ./.docker/prod/app/Dockerfile
    hostname: client
    expose:
      - 3000
    networks:
      - client
      - gateway
    restart: unless-stopped
