version: '3.8'

# List of used networks
networks:
  client:
    driver: overlay
    name: client

  api:
    driver: overlay
    name: api

services:
  # The client application container
  app:
    build:
      context: ./
      dockerfile: ./.docker/prod/app/Dockerfile
    image: ${IMAGE_REGISTRY:-local}/client-app:${IMAGE_TAG:-latest}
    hostname: client
    networks:
      - client
      - api
    restart: unless-stopped
