version: '3.8'

networks:
  gateway:
    name: gateway
    external: true

services:
  reverse-proxy:
    build:
      context: ./.docker/prod/reverse-proxy
      dockerfile: Dockerfile
    image: ${IMAGE_REGISTRY:-local}/gateway-reverse-proxy:${IMAGE_TAG:-latest}
    volumes:
      - ./.docker/prod/reverse-proxy/ssl:/etc/nginx/ssl:ro
      - ./.docker/prod/reverse-proxy/acme:/var/www/acme:ro
    expose:
      - 8001
    ports:
      - "443:443"
      - "80:80"
    networks:
      - gateway
    restart: unless-stopped

  certbot:
    build:
      context: ./.docker/prod/certbot
      dockerfile: Dockerfile
    volumes:
      - ./.docker/prod/reverse-proxy/ssl:/etc/letsencrypt:rw
      - ./.docker/prod/reverse-proxy/acme:/var/www/acme:rw
