global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: cadvisor
    scrape_interval: 20s
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: nginx-exporter
    metrics_path: '/metrics'
    static_configs:
      - targets: ['nginx-exporter:9113']
