version: '3.8'

networks:
  gateway:
    name: gateway
    external: true

volumes:
  certs:
  vhost:
  html:
  acme:

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:latest
    container_name: nginx-proxy
    volumes:
      - 'certs:/etc/nginx/certs'
      - 'vhost:/etc/nginx/vhost.d'
      - 'html:/usr/share/nginx/html'
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: true
    ports:
      - "80:80"
      - "443:443"
    networks:
      - gateway
    restart: always

  acme-companion:
    container_name: nginx-proxy-acme
    volumes:
      - 'certs:/etc/nginx/certs'
      - 'vhost:/etc/nginx/vhost.d'
      - 'html:/usr/share/nginx/html'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - 'acme:/etc/acme.sh'
    environment:
      DEFAULT_EMAIL: ${DEFAULT_EMAIL}
    image: nginxproxy/acme-companion
    restart: always
