version: '3.8'

networks:
  gateway:
    name: gateway
    external: true

  api:
    name: api
    driver: overlay

volumes:
  postgres:
    driver: local

  redis:
    driver: local

services:
  app:
    image: ${IMAGE_REGISTRY:-local}/api-app:${IMAGE_TAG:-latest}
    build:
      context: ./
      dockerfile: ./.docker/prod/app/Dockerfile
    # TODO: add storage volume
    # volumes:
    #   - ./:/var/www/html
    links:
      - postgres
      - redis
    hostname: api
    networks:
      - gateway
      - api
    restart: unless-stopped

  queue:
    image: ${IMAGE_REGISTRY:-local}/api-queue:${IMAGE_TAG:-latest}
    build:
      context: ./.docker/prod/queue
      dockerfile: Dockerfile
    # TODO: add storage volume
    # volumes:
    #   - ./:/var/www/html
    links:
      - postgres
      - redis
    networks:
      - api
    restart: unless-stopped

  schedule:
    image: ${IMAGE_REGISTRY:-local}/api-schedule:${IMAGE_TAG:-latest}
    build:
      context: ./.docker/prod/schedule
      dockerfile: Dockerfile
    # TODO: add storage volume
    # volumes:
    #   - ./:/var/www/html
    links:
      - postgres
      - redis
    networks:
      - api
    restart: unless-stopped

  postgres:
    image: ${IMAGE_REGISTRY:-local}/api-postgres:${IMAGE_TAG:-latest}
    build:
      context: ./
      dockerfile: ./.docker/prod/postgres/Dockerfile
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - api
    restart: unless-stopped

  redis:
    image: ${IMAGE_REGISTRY:-local}/api-redis:${IMAGE_TAG:-latest}
    build:
      context: ./
      dockerfile: ./.docker/prod/redis/Dockerfile
    volumes:
      - redis:/data
    networks:
      - api
    restart: unless-stopped
